### ISSUE TITLE
Error when computing report for Regenie

### ISSUE THREAD

**Issue by filosi** [genepi/genomic-utils#5]
`  java.lang.NumberFormatException: For input string: "NA"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:651)
        at genepi.io.table.reader.AbstractTableReader.getDouble(AbstractTableReader.java:38)
        at genepi.io.table.reader.AbstractTableReader.getDouble(AbstractTableReader.java:30)
        at genepi.genomic.utils.commands.GwasReportCommand.createHtmlReport(GwasReportCommand.java:316)
        at genepi.genomic.utils.commands.GwasReportCommand.call(GwasReportCommand.java:216)
        at genepi.genomic.utils.commands.GwasReportCommand.call(GwasReportCommand.java:31)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at genepi.genomic.utils.App.main(App.java:38)
`

**Comment by lukfor** [comment]
Thanks Michele, should be fixed in https://github.com/genepi/genomic-utils/commit/2caabd9d9a834798aecc78701eb7616e5c0fc01f and is available with the next release 👍
